export const SEARCH_CATEGORIES = {
    types: [
        "Portfolio",
        "E-commerce",
        "Blog",
        "Landing Page",
        "Corporate",
        "SaaS",
        "Agency",
        "Personal",
        "Documentation",
    ],

    styles: [
        "Minimal",
        "Modern",
        "Creative",
        "Dark",
        "Retro",
        "Brutalist",
        "Experimental",
        "Elegant",
        "Playful",
    ],

    industries: [
        "Technology",
        "Fashion",
        "Food & Beverage",
        "Real Estate",
        "Healthcare",
        "Education",
        "Entertainment",
        "Finance",
        "Art & Design",
        "Travel",
    ],

    colors: [
        "Black",
        "White",
        "Gray",
        "Blue",
        "Green",
        "Red",
        "Yellow",
        "Purple",
        "Pink",
        "Orange",
        "Brown",
        "Teal",
    ],

    features: [
        "Responsive",
        "Animated",
        "Interactive",
        "Multilingual",
        "Accessible",
        "Dark Mode",
        "Search",
        "Filtering",
        "Authentication",
        "E-commerce",
    ],

    layouts: [
        "Single Page",
        "Multi Page",
        "Grid",
        "Masonry",
        "Fullscreen",
        "Split Screen",
        "Card Based",
        "Magazine",
        "Asymmetric",
    ],

    platforms: [
        "Next.js",
        "React",
        "Vue",
        "WordPress",
        "Webflow",
        "Shopify",
        "Wix",
        "Squarespace",
        "Custom",
    ],
};
