export const SEARCH_CATEGORIES = {
    tags: [
        "Minimal",
        "Creative",
        "Portfolio",
        "E-commerce",
        "Agency",
        "Dark",
        "Responsive",
        "Modern",
    ],
    colors: [
        "Black",
        "White",
        "Gray",
        "Red",
        "Blue",
        "Green",
        "Yellow",
        "Purple",
        "Pink",
        "Orange",
        "Brown",
        "Teal",
    ],
    types: [
        "Portfolio",
        "E-commerce",
        "Blog",
        "Agency",
        "SaaS",
        "Landing Page",
        "Corporate",
    ],
};
